### ISSUE TITLE
zcu102_dpu, zcu104_dpu don't have libraries to run dpu

### ISSUE THREAD

**Issue by wilderfield** [Xilinx/Vitis_Embedded_Platform_Source#6]
The zcu102_dpu, and zcu104_dpu platforms are great starting points, but why don't they come with the necessary libraries to run the DPU? Today, users must go through many steps to install glog, pybind, unilog, xir, vart, vitis-ai-libraries ... will those ever be included as recipes in the platform?

**Comment by imrickysu** [comment]
For 2019.2 zcu102_dpu and zcu104_dpu platforms, user needs to install additional projects because
1. The required library version was not included by PetaLinux
2. Some recipes were not open source yet. They were delivered by Vitis-AI repo as binary. 

Vitis base platforms will be Vitis-AI ready in the future.
